version: "3.8"

services:

  # group-eq-bot stands for registering TG events and writing those into events-database container
  group-eq-bot:
    image: group-eq-bot:latest
    container_name: group-eq-bot
    build:
      context: group_eq_bot
      dockerfile: Dockerfile
    restart: always
    networks:
      - group-eq-bot-network

  # events-database (ElasticSearch) stands for storing under indexes TG events, TG groups and TG users
  events-database:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: events-database
    restart: always
    networks:
      - group-eq-bot-network
    environment:
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - snapshots-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    depends_on:
      - group-eq-bot

  # events-database-manager (Kibana) stands for UI for managing & fetching | visualising data from events-database (ElasticSearch)
  events-database-manager:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: events-database-manager
    restart: always
    networks:
      - group-eq-bot-network
    environment:
      - ELASTICSEARCH_HOSTS=http://events-database:9200  # address of elasticsearch docker container which kibana will connect
    ports:
      - "5601:5601"
    depends_on:
     - group-eq-bot
     - events-database

volumes:
    snapshots-elasticsearch:
      driver: local

networks:
  group-eq-bot-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.136.0.0/24